### ISSUE TITLE
Publish a workflow to build a GDExtension for all platforms on the GitHub Marketplace

### ISSUE THREAD

**Issue by Ughuuu** [godotengine/godot-proposals#8579]
### Describe the project you are working on

Multiple GDExtensions

### Describe the problem or limitation you are having in your project

Having to write for each a build system as GitHub actions. Would also be cool if there were something officially made so that if things change the build system actions change and update also.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Update on existing https://github.com/godotengine/godot-cpp-template/blob/main/.github/workflows/builds.yml and support for all platforms and all build types and all features(with configurable options).

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams

It will add more build types:
- web and mobile
- Mac signing
- single and double precision builds
- iOS simulator builds
- Caching support
- Possible support for releases and versioning

Also the project has to be configured as a reusable action(I think).

### If this enhancement will not be used often, can it be worked around with a few lines of script?

It can be a separate repo if not approved in the godot-cpp-template one.

### Is there a reason why this should be core and not an add-on in the asset library?

Just so that people don't have to rewrite or copy paste the actions every time and can be reused easily.

**Comment by Calinou** [comment]
godot-cpp only intends to have official SCons and CMake support. SCons is the recommended option as it's the same buildsystem as Godot itself (and therefore receives the most maintenance), while CMake is ubiquitous in the C++ community.

**Comment by Ughuuu** [comment]
Right, maybe I worded it badly. I want to use the same build system, SCons for now, as that is what I'm interested in, and have actions that can be reused. So the goal with this would be to be able to reuse the actions from that repo in any other repo, similar to this:
https://github.com/marketplace/actions/godot-ci

So ideally I would in my GDExtension project that builds with SCons just run:

            - name: gdextension-ci
              uses: godot/gdextension-ci@4.2-stable
            
And have it build for all platforms, possibly with some input variables for how it should sign the Mac exports, etc.

**Comment by Ughuuu** [comment]
Worked on this a bit, and so far if we would reuse we could reuse either actions or workflows. Both come with pros and cons.

Right now what I am trying looks like this:

```
      - name: 🔗 GDExtension Build
        uses: ughuuu/godot-cpp-template/.github/actions/build@add-more-stuff/options-to-build
        with:
          platform: ${{ matrix.platform }}
          arch: ${{ matrix.arch }}
          godot-cpp-location: godot-cpp
          enable-double-precision-builds: false
          enable-debug-builds: false
          enable-clang-lint: true
          lint-path: src/**
          bin-path: bin
```

So you would call this from your workflow and it would build everything for all os'es you specify. Optionally it can do debug and double builds in same job(reason is if not it would generate too many builds if each would be it's own build).
